const express = require('express')
const app = express()
const Routes = express.Router()
const dotenv = require('dotenv')
const { getHomeContent } = require('./controller/home.controller')
const { getConnections, createConnection } = require('./controller/connections.controller')
const { getGroups, createGroup } = require('./controller/groups.controller')
const { getSettings, updateSettings } = require('./controller/setting.controller')
dotenv.config()

Routes.route('/')
    .get(getHomeContent)
Routes.route('/connections')
    .get(getConnections)
    .post(createConnection)
Routes.route('/groups')
    .get(getGroups)
    .post(createGroup)
Routes.route('/setting')
    .get(getSettings)
    .put(updateSettings)
app.use('/', Routes)
app.all('*', (req, res) => {
    res.send('404 Not Found. Please check url')
})

app.listen(process.env.SERVER_PORT, () => console.log(`Server listening on port ${process.env.SERVER_PORT}`))